volumes:
    pgdata:
    pgdataRep1:
    pgdataRep2:

services:
  backend:
    container_name: backend
    environment:
      DB_HOST: "pg"
      DB_PORT: 5432
      DB_USER: "user"
      DB_PASSWORD: "user"
      DB_NAME: "otus_db"
    build:
      context: backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: go run ./main.go -b 0.0.0.0
    networks:
      - otus_net

  postgres-master:
    container_name: pgmaster
    image: postgres:17
    environment:
      POSTGRES_DB: "otus_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    mem_limit: 512m
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./Postgres:/docker-entrypoint-initdb.d # Инициализация таблиц
      - pgdata:/var/lib/postgresql/data # Папка, где postgres будет хранить данные
      #- ./volumes/Database/data:/var/lib/postgresql/data
      - ./volumes/Database/backups:/backups # Папка для бекапов
    networks:
      - otus_net

  postgres-standby1:
    container_name: pgslave
    image: postgres:17
    environment:
      POSTGRES_DB: "otus_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    mem_limit: 512m
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./Postgres:/docker-entrypoint-initdb.d # Инициализация таблиц
      - pgdataRep1:/var/lib/postgresql/data # Папка, где postgres будет хранить данные
      #- ./volumes/Database/data:/var/lib/postgresql/data
      - ./volumes/Database/backups:/backups # Папка для бекапов
    networks:
      - otus_net

  postgres-standby2:
    container_name: pgasyncslave
    image: postgres:17
    environment:
      POSTGRES_DB: "otus_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    mem_limit: 512m
    ports:
      - 5434:5432
    restart: always
    volumes:
      - ./Postgres:/docker-entrypoint-initdb.d # Инициализация таблиц
      - pgdataRep2:/var/lib/postgresql/data # Папка, где postgres будет хранить данные
      #- ./volumes/Database/data:/var/lib/postgresql/data
      - ./volumes/Database/backups:/backups # Папка для бекапов
    networks:
      - otus_net

  load_csv:   
    build: ./LoadCSV   
    depends_on: 
      - postgres-master
    networks:
      - otus_net

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:80
    depends_on: 
      - backend
    networks:
      - otus_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-ad
    environment: 
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports: 
      - "8888:80"
    networks:
      - otus_net 
networks:
  otus_net:
    driver: bridge

